import path from 'node:path';
import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { checkbox, confirm, select } from '@inquirer/prompts';
import { ensureDir } from '@/utils/fs.js';
import type { Locale } from '@/types/index.js';
import { isChineseLocale } from '@/utils/locale.js';

// 英文技能模板
const TEMPLATE_SKILL_EN = `---
name: Example Skill
description: This is an example skill generated by Skillink.
---

# Usage

Enable this skill to use it.
`;

// 中文技能模板
const TEMPLATE_SKILL_ZH = `---
name: 示例技能
description: 这是一个由 Skillink 生成的演示技能。
---

# 使用说明

激活此技能即可使用。
`;

// 默认支持的目标工具
const DEFAULT_TARGETS = [
  { name: 'Cursor', value: 'cursor', path: '.cursor/rules' },
  { name: 'Windsurf', value: 'windsurf', path: '.windsurf/rules' },
  { name: 'VSCode', value: 'vscode', path: '.vscode/skills' },
  { name: 'Gemini', value: 'gemini', path: '.gemini/skills' },
];

function getInitText(locale: Locale) {
  if (isChineseLocale(locale)) {
    return {
      title: '✨ Skillink 初始化',
      createSkillsDir: (skillsDir: string) =>
        `是否在 ${skillsDir} 创建技能目录？`,
      exampleSkillCreated: '✅ 已创建示例技能。',
      skillsDirExists: 'ℹ️  技能目录已存在。',
      selectTargets: '选择要同步的 AI 工具：',
      noTargets: '⚠️ 未选择任何目标。配置文件中的目标列表将为空。',
      overwriteConfig: '配置文件已存在。是否覆盖？',
      initCancelled: '❌ 初始化已取消。',
      configCreated: '✅ 已创建 skillink.config.ts',
      gitAdvice: (paths: string) =>
        `💡 Git 建议：请将目标目录（${paths}）加入 .gitignore，只提交 .agents/skills 与配置文件。`,
      nextStep: '\n👉 运行 "npx skillink sync" 开始同步！',
    };
  }

  return {
    title: '✨ Skillink Initialization',
    createSkillsDir: (skillsDir: string) =>
      `Create skills directory at ${skillsDir}?`,
    exampleSkillCreated: '✅ Example skill created.',
    skillsDirExists: 'ℹ️  Skills directory already exists.',
    selectTargets: 'Select AI tools to sync:',
    noTargets:
      '⚠️ No targets selected. The config will contain an empty targets list.',
    overwriteConfig: 'Configuration file already exists. Overwrite?',
    initCancelled: '❌ Initialization cancelled.',
    configCreated: '✅ Created skillink.config.ts',
    gitAdvice: (paths: string) =>
      `💡 Git tip: Add target directories (${paths}) to .gitignore. Commit only .agents/skills and config files.`,
    nextStep: '\n👉 Run "npx skillink sync" to start syncing!',
  };
}

/**
 * 初始化命令
 * @param cwd 当前工作目录
 */
export async function initCommand(cwd: string = process.cwd()) {
  const locale = await select<Locale>({
    message: 'Select language / 选择语言',
    choices: [
      { name: 'English', value: 'en' },
      { name: '简体中文', value: 'zh-CN' },
    ],
    default: 'en',
  });
  const text = getInitText(locale);
  const templateSkill = isChineseLocale(locale)
    ? TEMPLATE_SKILL_ZH
    : TEMPLATE_SKILL_EN;

  console.log(text.title);

  const skillsDir = path.join(cwd, '.agents', 'skills');
  const configFile = path.join(cwd, 'skillink.config.ts');

  // 1. 创建技能目录
  if (!existsSync(skillsDir)) {
    const create = await confirm({
      message: text.createSkillsDir(skillsDir),
      default: true,
    });
    if (create) {
      await ensureDir(skillsDir);
      // 创建示例技能
      const exampleDir = path.join(skillsDir, 'example-skill');
      await ensureDir(exampleDir);
      await fs.writeFile(path.join(exampleDir, 'SKILL.md'), templateSkill);
      console.log(text.exampleSkillCreated);
    }
  } else {
    console.log(text.skillsDirExists);
  }

  // 2. 选择目标工具
  const selectedTargets = await checkbox({
    message: text.selectTargets,
    choices: DEFAULT_TARGETS.map((t) => ({ name: t.name, value: t })),
  });

  if (selectedTargets.length === 0) {
    console.log(text.noTargets);
  }

  // 3. 生成配置文件
  if (existsSync(configFile)) {
    const overwrite = await confirm({
      message: text.overwriteConfig,
      default: false,
    });
    if (!overwrite) {
      console.log(text.initCancelled);
      return;
    }
  }

  const configContent = `import { defineConfig } from '@boses/skillink';

export default defineConfig({
  locale: '${locale}',
  source: '.agents/skills',
  targets: [
${selectedTargets
  .map(
    (t) => `    {
      name: '${t.value}',
      path: '${t.path}',
      enabled: true,
    },`,
  )
  .join('\n')}
  ],
});
`;

  await fs.writeFile(configFile, configContent);
  console.log(text.configCreated);
  if (selectedTargets.length > 0) {
    const targetPaths = selectedTargets.map((t) => t.path).join(', ');
    console.log(text.gitAdvice(targetPaths));
  }
  console.log(text.nextStep);
}
